{{- if not .Values.clickhouse.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse-product-analytics.fullname" . }}
  labels:
    {{- include "clickhouse-product-analytics.labels" . | nindent 4 }}
type: Opaque
stringData:
  PUBLIC_API_KEYS: {{ .Values.ingest.publicApiKeys | quote }}
  CLICKHOUSE_USER: {{ required "clickhouse.user is required" .Values.clickhouse.user | quote }}
  CLICKHOUSE_PASSWORD: {{ required "clickhouse.password is required" .Values.clickhouse.password | quote }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse-product-analytics.fullname" . }}-api-keys
  labels:
    {{- include "clickhouse-product-analytics.labels" . | nindent 4 }}
type: Opaque
stringData:
  PUBLIC_API_KEYS: {{ .Values.ingest.publicApiKeys | quote }}
{{- end }}
